%---------------------------------------------
%
% GUI Program
%
% by K.Kamura  06/02/2019
% 
%---------------------------------------------
clear
close all force

X_MIN = 200;
Y_MIN = 200;
WIDTH = 600;
HEIGHT = 250;
Figure_position = [X_MIN Y_MIN WIDTH HEIGHT];

%% figureの作成
H0 = uifigure('Position', Figure_position,...
    'NumberTitle','off',...
    'Name','ITD & ILD',...
    'MenuBar', 'none',...
    'Color', [0.6 0.7 1],...
    'Units','pixels',...
    'Visible','on');
v = get(0, 'MonitorPosition');

%% ラベル
label1 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-80 500 100],...
    'Text', 'ILD');
label1.FontSize = 20;
label2 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-185 500 100],...
    'Text', 'ITD');
label2.FontSize = 20;
label3 = uilabel(H0,...
    'Position', [WIDTH-40 HEIGHT-140 100 100],...
    'Text', '[dB]');
label4 = uilabel(H0,...
    'Position', [WIDTH-40 HEIGHT-220 100 100],...
    'Text', '[μs]');

%% スライダ
sld = uislider(H0,...
    'Position', [WIDTH/2-250 HEIGHT-70 500 3]);
sld.Limits = [-20 20];
sld_itd = uislider(H0,...
    'Position', [WIDTH/2-250 HEIGHT-170 500 3]);
sld_itd.Limits = [-1000 1000];

%% リセットボタン
button_ild = uibutton(H0,...
    'Position', [WIDTH-150 HEIGHT-50 80 30],...
    'Text', 'Clear ILD',...
    'ButtonPushedFcn',@(button_ild, event) reset_value(sld));

button_itd = uibutton(H0,...
    'Position', [WIDTH-150 HEIGHT-150 80 30],...
    'Text', 'Clear ITD',...
    'ButtonPushedFcn',@(button_itd, event) reset_value(sld_itd));

%% play
button_play = uibutton(H0,...
    'Position', [WIDTH-580 HEIGHT-50 80 30],...
    'Text', 'Play',...
    'ButtonPushedFcn',@(button_play, event) ilditd(sld, sld_itd));

function reset_value(obj)
obj.Value = 0;
end