clear
close all force

X_MIN = 200;
Y_MIN = 200;
WIDTH = 600;
HEIGHT = 500;
Figure_position = [X_MIN Y_MIN WIDTH HEIGHT];

H0 = figure('Position', Figure_position,...
    'NumberTitle', 'off',...
    'Name', 'ITD & ILD',...
    'MenuBar', 'none',...
    'Color', 'w',...
    'Units', 'pixels',...
    'Visible', 'on');

label1 = label(H0,...
    'Position', [WIDTH/2-10 HEIGHT-70 500 100],...
    'Text', 'ILD');