%---------------------------------------------
%
% GUI Program
%
% by K.Kamura  07/06/2019
% 
%---------------------------------------------
clear
close all force

X_MIN = 200;
Y_MIN = 200;
WIDTH = 600;
HEIGHT = 600;
Figure_position = [X_MIN Y_MIN WIDTH HEIGHT];
color = [0.6 0.7 1];

%% figureの作成
H0 = uifigure('Position', Figure_position,...
    'NumberTitle','off',...
    'Name','ITD & ILD',...
    'MenuBar', 'none',...
    'Color', color,...
    'Units','pixels',...
    'Visible','on');
v = get(0, 'MonitorPosition');

%% ラベル
label1 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-80 500 100],...
    'Text', 'ILD',...
    'FontSize', 20);
label2 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-185 500 100],...
    'Text', 'ITD',...
    'FontSize', 20);
label3 = uilabel(H0,...
    'Position', [WIDTH-35 HEIGHT-141 100 100],...
    'Text', '[dB]');
label4 = uilabel(H0,...
    'Position', [WIDTH-30 HEIGHT-240 100 100],...
    'Text', '[μs]');
label5 = uilabel(H0,...
    'Position', [WIDTH/2+50 HEIGHT-80 500 100],...
    'Text', '0 [dB]',...
    'fontsize', 20);
label6 = uilabel(H0,...
    'Position', [WIDTH/2+50 HEIGHT-185 500 100],...
    'Text', '0 [μs]',...
    'fontsize', 20);

%% Stop & Keep Button
button_stop = uibutton(H0, 'state',...
    'Position', [WIDTH-500 HEIGHT-50 80 30],...
    'Text', 'Stop');

button_keep = uibutton(H0, 'state',...
    'Position', [WIDTH-180 HEIGHT-50 80 30],...
    'BackgroundColor', [0.5 1 0.5],...
    'Text', 'Both');

%% スライダ
sld_ild = uislider(H0,...
    'Position', [WIDTH/2-250 HEIGHT-70 500 3],...
    'Limits', [-20 20]);

sld_itd = uislider(H0,...
    'Position', [WIDTH/2-250 HEIGHT-170 500 3],...
    'Limits', [-1000 1000],...
    'ValueChangingFcn',@(sld_itd, event)updatesld_ild(button_keep, sld_itd, sld_ild, event));

sld_ild.ValueChangingFcn = @(sld_ild,event) updatesld_itd(button_keep, sld_itd, sld_ild, event);

%% Reset Button
color_bt = [0.5 1 1];
button_ild = uibutton(H0,...
    'Position', [WIDTH-90 HEIGHT-50 80 30],...
    'Text', 'Clear ILD',...
    'BackgroundColor', color_bt,...
    'ButtonPushedFcn',@(button_ild, event) reset_value(sld_ild));

button_itd = uibutton(H0,...
    'Position', [WIDTH-90 HEIGHT-150 80 30],...
    'Text', 'Clear ITD',...
    'BackgroundColor', color_bt,...
    'ButtonPushedFcn',@(button_itd, event) reset_value(sld_itd));

%% Play Button
button_play = uibutton(H0,...
    'Position', [WIDTH-590 HEIGHT-50 80 30],...
    'Text', 'Play',...
    'ButtonPushedFcn',@(button_play, event) ilditd2(sld_ild, sld_itd, label5, label6, button_stop));

<<<<<<< HEAD
%% Answer Button
ax = uiaxes(H0,...
    'Pos', [50 0 500 390],...
    'Color', color,...
    'BackgroundColor', color,...
    'Visible', 'off',...
    'CameraPosition', [450 350 17.321],...
    'CameraPositionMode', 'manual');
A = imread('image1.jpeg');
image(ax, A);

w = 300;
color = [0.7 0.8 1];

for i = 1:7
    for j = 1:4
        if (i == 1 || i == 7) && (j == 1 || j == 3)
            continue
        elseif j == 4 && (i == 1 || i == 2 || i == 6 || i == 7)
            continue
        else
            button_ans(i, j) = uibutton(H0,...
                'Pos', [40+60*i 300-60*j 45 45],...
                'BackgroundColor', color,...
                'ButtonPushedFcn', @(button_ans, event) answer(i, j, sld_itd, sld_ild),...
                'Text', '');
        end
    end
end

%% 回答を表示する関数
function answer(i, j, sld_itd, sld_ild)
disp(['pos = (' num2str(i) ', ' num2str(5-j) ')'])
% pos = zeros(4, 7);
% pos(j, i) = 1;
% disp(pos)
disp(['ITD = ' num2str(sld_itd.Value) ' [db]'])
disp(['ILD = ' num2str(sld_ild.Value) ' [μs]' newline])
end

%% Bothボタンが押されたとき、itdのスライダも同時に動かす関数
function updatesld_itd(keep, sld_itd, sld_ild, event)
if keep.Value == 1
    sld_itd.Value = event.Value * 50;
    sld_ild.Value = event.Value;
else
    sld_ild.Value = event.Value;
end
end

%% Bothボタンが押されたとき、ildのスライダも同時に動かす関数
function updatesld_ild(keep, sld_itd, sld_ild, event)
if keep.Value == 1
    sld_ild.Value = event.Value * 0.02;
    sld_itd.Value = event.Value;
else
    sld_itd.Value = event.Value;
end
end

%% スライダの値を0にリセットする関数
=======
>>>>>>> b348d25435a5932f225e4441d5c4497cfd6f7459
function reset_value(obj)
obj.Value = 0;
end