%---------------------------------------------
%
% GUI Program
%
% by K.Kamura  07/06/2019
% 
%---------------------------------------------
clear
close all force

X_MIN = 200;
Y_MIN = 200;
WIDTH = 600;
HEIGHT = 250;
Figure_position = [X_MIN Y_MIN WIDTH HEIGHT];

%% figureの作成
H0 = uifigure('Position', Figure_position,...
    'NumberTitle','off',...
    'Name','ITD & ILD',...
    'MenuBar', 'none',...
    'Color', [0.6 0.7 1],...
    'Units','pixels',...
    'Visible','on');
v = get(0, 'MonitorPosition');

%% ラベル
label1 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-80 500 100],...
    'Text', 'ILD');
label1.FontSize = 20;
label2 = uilabel(H0,...
    'Position', [WIDTH/2-10 HEIGHT-185 500 100],...
    'Text', 'ITD');
label2.FontSize = 20;
label3 = uilabel(H0,...
    'Position', [WIDTH-35 HEIGHT-141 100 100],...
    'Text', '[dB]');
label4 = uilabel(H0,...
    'Position', [WIDTH-30 HEIGHT-240 100 100],...
    'Text', '[μs]');
label5 = uilabel(H0,...
    'Position', [WIDTH/2+50 HEIGHT-80 500 100],...
    'Text', '0 [dB]',...
    'fontsize', 20);
label6 = uilabel(H0,...
    'Position', [WIDTH/2+50 HEIGHT-185 500 100],...
    'Text', '0 [μs]',...
    'fontsize', 20);

%% Stop & Keep Button
button_stop = uibutton(H0, 'state',...
    'Position', [WIDTH-500 HEIGHT-50 80 30],...
    'Text', 'Stop');

button_keep = uibutton(H0, 'state',...
    'Position', [WIDTH-410 HEIGHT-50 80 30],...
    'Text', 'Keep');

%% スライダ
sld_ild = uislider(H0,...
    'Position', [WIDTH/2-250 HEIGHT-70 500 3],...
    'Limits', [-20 20]);

sld_itd = uislider(H0,...
    'Position', [WIDTH/2-250 HEIGHT-170 500 3],...
    'Limits', [-1000 1000],...
    'ValueChangingFcn',@(sld_itd, event)updatesld_ild(button_keep, sld_itd, sld_ild, event));

sld_ild.ValueChangingFcn = @(sld_ild,event) updatesld_itd(button_keep, sld_itd, sld_ild, event);

%% リセットボタン
button_ild = uibutton(H0,...
    'Position', [WIDTH-110 HEIGHT-50 80 30],...
    'Text', 'Clear ILD',...
    'ButtonPushedFcn',@(button_ild, event) reset_value(sld_ild));

button_itd = uibutton(H0,...
    'Position', [WIDTH-110 HEIGHT-150 80 30],...
    'Text', 'Clear ITD',...
    'ButtonPushedFcn',@(button_itd, event) reset_value(sld_itd));

%% Play Button
button_play = uibutton(H0,...
    'Position', [WIDTH-590 HEIGHT-50 80 30],...
    'Text', 'Play',...
    'ButtonPushedFcn',@(button_play, event) ilditd2(sld_ild, sld_itd, label5, label6, button_stop));

function updatesld_itd(keep, sld_itd, sld_ild, event)
if keep.Value == 1
    sld_itd.Value = event.Value * 50;
    sld_ild.Value = event.Value;
else
    sld_ild.Value = event.Value;
end
end

function updatesld_ild(keep, sld_itd, sld_ild, event)
if keep.Value == 1
    sld_ild.Value = event.Value * 0.02;
    sld_itd.Value = event.Value;
else
    sld_itd.Value = event.Value;
end
end

function reset_value(obj)
obj.Value = 0;
end