clear
close all

f = figure('WindowStyle', 'docked');
v = get(gcf, 'Position');
A = axes(f,...
    'Pos', [0.05 0.2 0.79 0.73]);
H = animatedline(A, 'Color', 'b');
bt_select = uicontrol(f,...
    'Style', 'pushbutton',...
    'Pos', [v(3)-170 55 50 20],...
    'String', 'Select',...
    'Callback', '[filename, pathname] = uigetfile(''*.*'', ''Load Sound Data'');');
bt_stop = uicontrol(f,...
    'Style', 'togglebutton',...
    'Pos', [v(3)-170 5 50 20],...
    'String', 'Stop');
bt_play = uicontrol(f,...
    'Style', 'pushbutton',...
    'Pos', [v(3)-170 30 50 20],...
    'String', 'Play',...
    'CallBack', 'Play(H, bt_stop, filename, pathname)');